export const DEFAULT_PROJECTS = [
    {
        title: 'Edu Verifier',
        desc: 'A Fraud Certificates Detection Application',
        tech: ['React', 'Node.js', 'MongoDB', 'Express'],
        github: 'https://github.com/',
        live: '#',
        gradient: 'linear-gradient(135deg,#5c6bff,#a78bfa)',
        letter: 'E',
        featured: true,
    },
    {
        title: 'Find My Items',
        desc: 'Find the Lost items in the Campus',
        tech: ['React', 'Firebase', 'MangoDB'],
        github: 'https://github.com/Narasingarao07/findmy-campus.git',
        live: 'https://findmy-campus.lovable.app/auth',
        gradient: 'linear-gradient(135deg,#10b981,#34d399)',
        letter: 'F',
        featured: true,
    },
    {
        title: 'Sai Ganapathi College Website',
        desc: 'became a part of a team to developa responsive  website showcasing courses, departments, admission portols lot more.',
        tech: ['Django', 'Postgres', 'DigitalOcean', 'Socket.io'],
        github: 'https://github.com/',
        live: '#',
        gradient: 'linear-gradient(135deg,#f59e0b,#fbbf24)',
        letter: 'C',
        featured: true,
    },
    {
        title: 'AI Resume Builder',
        desc: 'AI-powered resume builder that generates tailored resumes based on job descriptions.',
        tech: ['React', 'OpenAI API', 'Python', 'FastAPI'],
        github: 'https://github.com/',
        live: '#',
        gradient: 'linear-gradient(135deg,#ef4444,#f87171)',
        letter: 'AI',
        featured: false,
    },
    {
        title: 'Weather Now',
        desc: 'Beautiful weather app with real-time forecasts, animated icons, and location search.',
        tech: ['JavaScript', 'OpenWeather API', 'CSS3'],
        github: 'https://github.com/Narasingarao07/Weather_map',
        live: '#',
        gradient: 'linear-gradient(135deg,#3b82f6,#60a5fa)',
        letter: 'W',
        featured: false,
    },
    {
        title: 'Library Management System',
        desc: 'A comprehensive library management system that handles book management, member management, and transaction management.',
        tech: ['Django', 'SQLite', 'Python'],
        github: 'https://github.com/Narasingarao07/library_management',
        live: null,
        gradient: 'linear-gradient(135deg,#8b5cf6,#a78bfa)',
        letter: 'T',
        featured: false,
    },
];

export const DEFAULT_EDUCATION = [
    {
        title: 'B.Tech in Computer Science & Engineering',
        org: 'GVPCE — Gayatri Vidya Parishad College Of Engineering',
        period: '2024 – Present',
        location: 'Andhra Pradesh, India',
        badge: 'CGPA: 8.2/10',
        desc: 'Focused on full-stack development, data structures, algorithms, and cloud computing.',
        type: 'edu',
        icon: 'book',
    },
    {
        title: 'Diploma in Computer Science & Engineering',
        org: 'Sai Ganapathi Polytechic College',
        period: '2021 – 2024',
        location: 'Andhra Pradesh, India',
        badge: 'Score: 9.4/10',
        desc: 'Strong foundation in Mathematics, Physics, and Computer Science fundamentals.',
        type: 'edu',
        icon: 'book',
    },
    {
        title: '10th SSC',
        org: 'AP MODEL SCHOOL - O.V.PETA',
        period: '2018 - 2020',
        location: 'Andhra Pradesh, India',
        badge: 'CGPA: 9.7/10',
        desc: 'Focused on full-stack development, data structures, algorithms, and cloud computing.',
        type: 'edu',
        icon: 'book',
    },
];

export const DEFAULT_EXPERIENCE = [
    {
        title: 'Full-Stack Developer Intern',
        org: 'Millinium Software Solutions',
        period: 'May 2024 – Jul 2024',
        location: 'Remote',
        desc: 'Built REST APIs with Node.js & Express, contributed to React dashboard for client reporting.',
        type: 'exp',
        icon: 'briefcase',
    },
    {
        title: 'Open Source Contributor',
        org: 'GitHub Community',
        period: '2023 – Present',
        location: 'Remote',
        desc: 'Bug fixes and features in several React and Python open-source projects.',
        type: 'exp',
        icon: 'briefcase',
    },
];

export const DEFAULT_CERTS = [
    {
        title: 'Python FullStack',
        issuer: 'Millinium Software Solutions Pvt.Ltd.',
        date: 'Issued: 2024',
        icon: '🏆',
        tags: ['Python', 'Django', 'Pandas', 'Numpy', 'Matplotlib'],
        link: '#',
        color: '#3b82f6',
    },
    {
        title: 'AWS Cloud Solutions Architect',
        issuer: 'Amazon Web Services',
        date: 'Issued: Jul 2025',
        icon: '☁️',
        tags: ['AWS Services', 'Cloud Architecture', 'Security'],
        link: '#',
        color: '#f59e0b',
    },
    {
        title: 'OCI 2025 Certified Developer',
        issuer: 'ORACLE',
        date: 'Issued: Oct 2025',
        icon: '🏢',
        tags: ['Cloud Native', 'Serverless', 'Scalability'],
        link: '#',
        color: '#ef4444',
    },
    {
        title: 'Rocket Propulsion Dynamics',
        issuer: 'Kodacy (in collab with ISRO)',
        date: 'Issued: May 2025',
        icon: '🚀',
        tags: ['Aerospace', 'Physics'],
        link: '#',
        color: '#a78bfa',
    },
    {
        title: 'Python for Data Science',
        issuer: 'IBM',
        date: 'Issued: Mar 2023',
        icon: '🐍',
        tags: ['Python', 'Data Analysis'],
        link: '#',
        color: '#10b981',
    },
];
